# Generated by Django 6.0.4 on 2026-05-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_category_owner_lesson_owner_subcategory_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='parent',
        ),
    ]
